### ISSUE TITLE
bug: inconsistent fields

### ISSUE THREAD

**Issue by bengnar** [JaneliaSciComp/JRCLUST#112]
Using 4.0.0-alpha.6

After `Finished computing cluster quality scores `I receive the following error:

#### Output of `ver`
----------------------------------------------------------------------------------------------------
MATLAB Version: 9.2.0.538062 (R2017a)
Operating System: Microsoft Windows 10 Pro Version 10.0 (Build 17134)
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------

#### Output of `gpuDevice`
                      Name: 'GeForce GTX TITAN X'
                     Index: 1
         ComputeCapability: '5.2'
            SupportsDouble: 1
             DriverVersion: 10.1000
            ToolkitVersion: 8
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 1.2885e+10
           AvailableMemory: 8.9930e+09
       MultiprocessorCount: 24
              ClockRateKHz: 1076000
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1

#### The command you used
jrc detect-sort myparam.prm

#### Console output

Error using  ~= 
Matrix dimensions must agree.

Error in jrclust.sort.DensityPeakClustering/inconsistentFields
(line 9)
        dupes = find(obj.spikeClusters(obj.clusterCenters) ~=
        (1:obj.nClusters)');

Error in jrclust.interfaces.Clustering/commit (line 20)
    ic = obj.inconsistentFields();

Error in jrclust.sort.DensityPeakClustering/autoMerge (line
51)
    obj.commit(sprintf('%s;autoMerge (maxUnitSim %0.2f)',
    datestr(now, 31), obj.hCfg.maxUnitSim));

Error in jrclust.sort.SortController/sort (line 54)
            hClust.autoMerge();

Error in JRC/sort (line 34)
    sRes = obj.hSort.sort(obj.res);

Error in JRC/run (line 20)
        obj.sort();

Error in jrc (line 21)
        hJRC.run();

**Comment by aliddell** [comment]
Can you try downloading the latest release and seeing if you still see this error?
