### ISSUE TITLE
bug: preview mode doesn't load all samples

### ISSUE THREAD

**Issue by bengnar** [JaneliaSciComp/JRCLUST#113]
Using JRCLUST-4.0.0-beta.1 

Out of  1678097 samples, preview only loads 900000 samples. 

#### Output of `ver`
----------------------------------------------------------------------------------------------------
MATLAB Version: 9.2.0.538062 (R2017a)
Operating System: Microsoft Windows 10 Pro Version 10.0 (Build 17134)
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------

#### Output of `gpuDevice`
                      Name: 'GeForce GTX TITAN X'
                     Index: 1
         ComputeCapability: '5.2'
            SupportsDouble: 1
             DriverVersion: 10.1000
            ToolkitVersion: 8
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 1.2885e+10
           AvailableMemory: 8.9930e+09
       MultiprocessorCount: 24
              ClockRateKHz: 1076000
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1

#### The command you used
jrc detect-sort myparam.prm

**Comment by aliddell** [comment]
This is controlled by two parameters: [nLoadsMaxPreview](https://jrclust.readthedocs.io/en/latest/parameters/index.html#nloadsmaxpreview) (default 30) and [nSecsLoadPreview](https://jrclust.readthedocs.io/en/latest/parameters/index.html#nsecsloadpreview) (default 1). At 30 kHz 90000 samples is 30 seconds. In your case, if you want to see the whole thing you can set your nLoadsMaxPreview to 56 ( = `ceil(1678097/30000)`).
