### ISSUE TITLE
loadTimeLimits seems to be in samples and not seconds

### ISSUE THREAD

**Issue by WeissShahaf** [JaneliaSciComp/JRCLUST#122]
when i use loadTimeLimits, preprocessing ends extremely fast, and mostly with errors- because no spikes are detected.
when i use it with the calculated number of samples it does not crash. so i think it is in samples and not in seconds as stated

If you have a usage or support question, come join our [Gitter](https://gitter.im/JRCLUST/community) and ask your question there.
If you found a bug, please provide **all** of the following:

#### Output of `ver`
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.4.0.813654 (R2018a)
MATLAB License Number: unknown
Operating System: Microsoft Windows 10 Enterprise Version 10.0 (Build 16299)
Java Version: Java 1.8.0_144-b01 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.4         (R2018a)
Simulink                                              Version 9.1         (R2018a)
Aerospace Blockset                                    Version 3.21        (R2018a)
Aerospace Toolbox                                     Version 2.21        (R2018a)
Antenna Toolbox                                       Version 3.1         (R2018a)
Audio System Toolbox                                  Version 1.4         (R2018a)
Automated Driving System Toolbox                      Version 1.2         (R2018a)
Bioinformatics Toolbox                                Version 4.10        (R2018a)
Communications System Toolbox                         Version 6.6         (R2018a)
Computer Vision System Toolbox                        Version 8.1         (R2018a)
Control System Toolbox                                Version 10.4        (R2018a)
Curve Fitting Toolbox                                 Version 3.5.7       (R2018a)
DSP System Toolbox                                    Version 9.6         (R2018a)
Data Acquisition Toolbox                              Version 3.13        (R2018a)
Database Toolbox                                      Version 8.1         (R2018a)
Datafeed Toolbox                                      Version 5.7         (R2018a)
Econometrics Toolbox                                  Version 5.0         (R2018a)
Embedded Coder                                        Version 7.0         (R2018a)
Filter Design HDL Coder                               Version 3.1.3       (R2018a)
Financial Instruments Toolbox                         Version 2.7         (R2018a)
Financial Toolbox                                     Version 5.11        (R2018a)
Fixed-Point Designer                                  Version 6.1         (R2018a)
Fuzzy Logic Toolbox                                   Version 2.3.1       (R2018a)
GPU Coder                                             Version 1.1         (R2018a)
GUI Layout Toolbox                                    Version 2.3.4       (R2018b)
GUI Layout Toolbox                                    Version 1.17        (R2013b)
GUI Layout Toolbox                                    Version 1.17        (R2013b)
Global Optimization Toolbox                           Version 3.4.4       (R2018a)
HDL Coder                                             Version 3.12        (R2018a)
HDL Verifier                                          Version 5.4         (R2018a)
Image Acquisition Toolbox                             Version 5.4         (R2018a)
Image Processing Toolbox                              Version 10.2        (R2018a)
Instrument Control Toolbox                            Version 3.13        (R2018a)
LTE HDL Toolbox                                       Version 1.1         (R2018a)
LTE System Toolbox                                    Version 2.6         (R2018a)
MATLAB Coder                                          Version 4.0         (R2018a)
MATLAB Compiler                                       Version 6.6         (R2018a)
MATLAB Compiler SDK                                   Version 6.5         (R2018a)
MATLAB Report Generator                               Version 5.4         (R2018a)
Mapping Toolbox                                       Version 4.6         (R2018a)
Model Predictive Control Toolbox                      Version 6.1         (R2018a)
Model-Based Calibration Toolbox                       Version 5.4         (R2018a)
Neural Network Toolbox                                Version 11.1        (R2018a)
OPC Toolbox                                           Version 4.0.5       (R2018a)
Optimization Toolbox                                  Version 8.1         (R2018a)
Parallel Computing Toolbox                            Version 6.12        (R2018a)
Partial Differential Equation Toolbox                 Version 3.0         (R2018a)
Phased Array System Toolbox                           Version 3.6         (R2018a)
Polyspace Bug Finder                                  Version 2.5         (R2018a)
Polyspace Code Prover                                 Version 9.9         (R2018a)
Powertrain Blockset                                   Version 1.3         (R2018a)
Predictive Maintenance Toolbox                        Version 1.0         (R2018a)
RF Blockset                                           Version 7.0         (R2018a)
RF Toolbox                                            Version 3.4         (R2018a)
Risk Management Toolbox                               Version 1.3         (R2018a)
Robotics System Toolbox                               Version 2.0         (R2018a)
Robust Control Toolbox                                Version 6.4.1       (R2018a)
Signal Processing Toolbox                             Version 8.0         (R2018a)
SimBiology                                            Version 5.8         (R2018a)
SimEvents                                             Version 5.4         (R2018a)
Simscape                                              Version 4.4         (R2018a)
Simscape Driveline                                    Version 2.14        (R2018a)
Simscape Electronics                                  Version 2.13        (R2018a)
Simscape Fluids                                       Version 2.4         (R2018a)
Simscape Multibody                                    Version 5.2         (R2018a)
Simscape Power Systems                                Version 6.9         (R2018a)
Simulink 3D Animation                                 Version 8.0         (R2018a)
Simulink Check                                        Version 4.1         (R2018a)
Simulink Code Inspector                               Version 3.2         (R2018a)
Simulink Coder                                        Version 8.14        (R2018a)
Simulink Control Design                               Version 5.1         (R2018a)
Simulink Coverage                                     Version 4.1         (R2018a)
Simulink Design Optimization                          Version 3.4         (R2018a)
Simulink Design Verifier                              Version 3.5         (R2018a)
Simulink Desktop Real-Time                            Version 5.6         (R2018a)
Simulink PLC Coder                                    Version 2.5         (R2018a)
Simulink Real-Time                                    Version 6.8         (R2018a)
Simulink Report Generator                             Version 5.4         (R2018a)
Simulink Requirements                                 Version 1.1         (R2018a)
Simulink Test                                         Version 2.4         (R2018a)
Spreadsheet Link                                      Version 3.3.3       (R2018a)
Stateflow                                             Version 9.1         (R2018a)
Statistics and Machine Learning Toolbox               Version 11.3        (R2018a)
Symbolic Math Toolbox                                 Version 8.1         (R2018a)
System Identification Toolbox                         Version 9.8         (R2018a)
Text Analytics Toolbox                                Version 1.1         (R2018a)
Trading Toolbox                                       Version 3.4         (R2018a)
Vehicle Dynamics Blockset                             Version 1.0         (R2018a)
Vehicle Network Toolbox                               Version 4.0         (R2018a)
Vision HDL Toolbox                                    Version 1.6         (R2018a)
WLAN System Toolbox                                   Version 1.5         (R2018a)
Wavelet Toolbox                                       Version 5.0         (R2018a)
#### Output of `gpuDevice`
ans = 
  CUDADevice with properties:

                      Name: 'Quadro P5000'
                     Index: 1
         ComputeCapability: '6.1'
            SupportsDouble: 1
             DriverVersion: 10.1000
            ToolkitVersion: 9
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 1.6106e+10
           AvailableMemory: 1.3152e+10
       MultiprocessorCount: 20
              ClockRateKHz: 1733500
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 0
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1
#### The command you used
(e.g., `jrc detect-sort myparam.prm`)
jrc detect-sort
#### Console output
Index in position 2 exceeds array bounds (must not exceed 1).
Error in jrclust.detect.DetectController/findSecondaryPeaks (line 7)
    spikeWindows2 = spikeWindows(:, evtNeighbors, :);
Error in jrclust.detect.DetectController/samplesToWindows (line 57)
        [spikeSites2, spikeSites3] = obj.findSecondaryPeaks(spikesFilt,
        spikeSites);
Error in jrclust.detect.DetectController/detectOneRecording (line 194)
        loadData = obj.samplesToWindows(loadData);
Error in jrclust.detect.DetectController/detect (line 66)
        recData = obj.detectOneRecording(hRec, [rawFid, filtFid], impTimes,
        impSites, siteThresh);
Error in JRC/detect (line 16)
    dRes = obj.hDetect.detect();
Error in JRC/run (line 13)
        obj.detect();
Error in jrc (line 20)
        hJRC.run();

**Comment by aliddell** [comment]
Thanks for spotting (and reporting). A fix is inbound.
