### ISSUE TITLE
Red traces does not disappear after merging

### ISSUE THREAD

**Issue by hidehikoinagaki** [JaneliaSciComp/JRCLUST#132]
After merging in manual sorting, the red traces indicating secondly selected cluster does not disappear until I select another cluster. It is not a big issue but just pointing out.

JRCLUST v4.0.1 "Edward" (ead74e2)
![bug](https://user-images.githubusercontent.com/57011270/67586854-97d76280-f720-11e9-8d3a-2b0bbbdf134b.png)

**Comment by aliddell** [comment]
This should be fixed as of the latest commit.
