### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by jenniferColonell** [JaneliaSciComp/JRCLUST#142]
Hi Alan!

I've made fixes for these in my fork of the current repo. (https://github.com/jenniferColonell/JRCLUST/commits/master/%2Bjrclust)

In the latest version (88d46cd)...

GetSecondaryPeaks method declaration is now in the wrong class (i.e. still in jrc.sort, but should now be in jrc.interfaces)?

Meta data parsing needs to be fixed to be compatible with metadata created by catGT (need to allow for extra "=" characters)

Need to add update of number of clusters in updateFigWav.m -- after merges in TemplateClustering, was winding up with the wrong number.

Also adding automerging by waveform similarity calculation for TemplateClustering.

thanks!

**Comment by aliddell** [comment]
Great! Can you open a pull request?
