### ISSUE TITLE
Scale change in waveform view causes an error

### ISSUE THREAD

**Issue by jenniferColonell** [JaneliaSciComp/JRCLUST#147]
If you have a usage or support question, come join our [Gitter](https://gitter.im/JRCLUST/community) and ask your question there.
If you found a bug, please provide **all** of the following:

#### Output of `jrc version`

JRCLUST v4.0.1 "Edward" (c584685)

#### If manually sorting, what it is you tried to do

Shift-up in waveform view (to change scale). Shift-down arrow has same result

#### Console output

Not enough input arguments.

Error in jrclust.views.plotFigWav (line 29)
        hFigWav = plotSpikeWaveforms(hFigWav, hClust, maxAmp, channel_idx);

Error in jrclust.views.rescaleFigWav (line 4)
    jrclust.views.plotFigWav(hFigWav, hClust, maxAmp);

Error in jrclust.curate.CurateController/keyPressFigWav (line 14)
            obj.maxAmp = jrclust.views.rescaleFigWav(hFigWav, obj.hClust, obj.maxAmp, sqrt(2)^-factor);

Error in jrclust.curate.CurateController/plotAllFigures>@(varargin)obj.keyPressFigWav(varargin{:}) (line 40)
        hFigWav.hFunKey = @obj.keyPressFigWav;
 
Error while evaluating Figure KeyPressFcn.

**Comment by aliddell** [comment]
Fixed in f7c3c028904c0fe44d93eb2257777b915924b511.
