### ISSUE TITLE
error importing kilosort results

### ISSUE THREAD

**Issue by Liawh** [JaneliaSciComp/JRCLUST#18]
Hi James, 
    jrclust cannot find rho after importing kilosort results into it. I use jrc3 import-ksort x.prm or jrc3 import-ksort-sort x.prm and the code runs to the end without any error. However, when opening the gui, I got an error: 

Reference to non-existent field 'rho'.

Error in jrc3>detrend_local_ (line 17579)
    x =3D log10(S_clu.rho);

Error in jrc3>plot_FigRD_ (line 3879)
        [icl, x, y] =3D detrend_local_(S_clu, P, 0);

Error in jrc3>manual_ (line 3605)
S0.S_clu =3D plot_FigRD_(S0.S_clu, P); % ask user before doing so

Error in jrc3 (line 185)
    manual_(P);

Could you check which part goes wrong or the problem only happens in my computer? I just update to the latest version (v3.2.5). Thank you in advance. 

Hua-Peng

**Comment by aliddell** [comment]
Hi. Support has been in flux for JRCLUST, and we're sorry for that. If you're still interested in importing KiloSort output, we have [a feature branch](https://github.com/JaneliaSciComp/JRCLUST/tree/kilosort) (`kilosort`) which fixes these problems. This has yet to be documented correctly, but you invoke it like so:

`jrc import-ksort /path/to/your/rez.mat sessionName`

where you supply the path to your `rez.mat` file output by KiloSort and you give it a `sessionName` (which is what you would normally name your `.prm` file.

If you're not still interested in importing KiloSort output into JRCLUST, please let me know here so I can close this issue. (Even better, if you _are_ still interested, please let me know here how it works for you.)
