### ISSUE TITLE
Bypass "Recording file format" GUI during batch

### ISSUE THREAD

**Issue by SPalestis** [JaneliaSciComp/JRCLUST#23]
I am trying to run a batch of 110 recordings, and the "Recording file format" GUI keeps coming up before each recording is analyzed.

I have manually inputted the values in mytemplate.prm file that the "Recording file format" GUI requires.

Any assistance would be much appreciated!

**Comment by jamesjun** [comment]
You are missing a .meta file to describe your .bin file. This can happen when you did not use SpikeGLX recording software designed for Janelia labs. This is a bug and should be fixed. 

-James

**Comment by SPalestis** [comment]
I just downloaded SpikeGLX from GitHub.

How do I go about processing all my bin files and create .meta files for them?

**Comment by SPalestis** [comment]
I tried your suggestion of making a text file that contains all the .prm files and it worked. 

Thank you!
