### ISSUE TITLE
Issue when running KiloSort

### ISSUE THREAD

**Issue by SPalestis** [JaneliaSciComp/JRCLUST#24]
I tried running KiloSort through JRC, and I got the following error. What input argument did I miss? 

![image](https://user-images.githubusercontent.com/35611792/38573727-f0c343ea-3cc4-11e8-8ce0-d447a51c3f52.png)

**Comment by SPalestis** [comment]
I figured out the previous error, the .bin file had to have the same file path.

I re-ran and got the following error:
![image](https://user-images.githubusercontent.com/35611792/38574767-a82a3604-3cc7-11e8-935f-202c38bd8847.png)
![image](https://user-images.githubusercontent.com/35611792/38574783-b1f333fc-3cc7-11e8-8dd5-09c8acc1ea45.png)

**Comment by aliddell** [comment]
Hi. Support has been in flux for JRCLUST, and we're sorry for that. If you're still interested in importing KiloSort output, we have [a feature branch](https://github.com/JaneliaSciComp/JRCLUST/tree/kilosort) (`kilosort`) which fixes these problems. This has yet to be documented correctly, but you invoke it like so:

`jrc import-ksort /path/to/your/rez.mat sessionName`

where you supply the path to your `rez.mat` file output by KiloSort and you give it a `sessionName` (which is what you would normally name your `.prm` file.

If you're not still interested in importing KiloSort output into JRCLUST, please let me know here so I can close this issue. (Even better, if you _are_ still interested, please let me know here how it works for you.)
