### ISSUE TITLE
Plotting PSTHs 

### ISSUE THREAD

**Issue by vncntprvst** [JaneliaSciComp/JRCLUST#3]
The two functions **maketrial** and **raster** do not generate anything and only return the Help and Documentation. Better documentation to use these functions and plot PSTHs in general would be appreciated. In addition, having the option to plot PSTHs from the Main GUI or the Manual GUI would be very convenient.
Thanks!

**Comment by jamesjun** [comment]
Thanks for the error report. I will add a documentation on how to use this
feature.

-James

--
J. James Jun, PhD
Consulting Scientist
HHMI - Janelia Research Campus
19700 Helix Dr, Ashburn, VA 20147
571.279.2327 | office: 2C.150
jamesjun@gmail.com

**Comment by vncntprvst** [comment]
Thanks!

**Comment by jamesjun** [comment]
I will update the maketrial command. I forgot to migrate this function in
the new version. You can manually set the timing by following the
instruction below:

https://github.com/JaneliaSciComp/JRCLUST/wiki/PSTH-viewing

--
J. James Jun, PhD
Consulting Scientist
HHMI - Janelia Research Campus
19700 Helix Dr, Ashburn, VA 20147
571.279.2327 | office: 2C.150
jamesjun@gmail.com
