### ISSUE TITLE
export_quality error

### ISSUE THREAD

**Issue by jenniferColonell** [JaneliaSciComp/JRCLUST#41]
when running jrc export-quality, get the error:
-------------------------------------------------------------------
Reference to non-existent field 'nClu'.

Error in export_quality_ (line 16)
    deal((1:S.nClu)', S.vrSnr_clu(:), S.clusterSites(:), S.nSpikesPerCluster(:), ...

Error in jrc (line 195)
        case {'export-quality', 'exportquality', 'quality'}, export_quality_(P);
---------------------------------------------------------------------------

Issue is just that the field ins S_clu (subfield of S) is actually named S_clu.nClusters, not S_clu.nClu.

**Comment by aliddell** [comment]
This should be fixed now -- can you check for me?

**Comment by jenniferColonell** [comment]
Looks good. Thanks, Alan!

I’ve run the importer successfully now, and at least verified that the clusters get read in and exported back out w/out any changes (yes, I know you tested that!). Very nice to be able to calculate the JRC quality metrics on the kilosort clusters for comparison.

jennifer
