### ISSUE TITLE
filtering during kilsort-import can't use GPU?

### ISSUE THREAD

**Issue by jenniferColonell** [JaneliaSciComp/JRCLUST#54]
Looks like the filtering operation when importing a kilosort session can't use the GPU (on my machine). I imagine we aren't limiting the memory correctly? Might be that MAX_BYTES_LOAD isn't getting calculated correctly for the GPU present?
CPU filtering is fine, but a little slow. 
The GPUs do get used to run the RL calculation.

Here's the command line warning:

Filtering spikes...GPU filtering failed. Trying CPU filtering.

**Comment by aliddell** [comment]
This is supposed to have been fixed in 798ebd5 -- do you have the latest commit?
