### ISSUE TITLE
Auto split

### ISSUE THREAD

**Issue by jup36** [JaneliaSciComp/JRCLUST#57]
I think there's an issue with this new auto-split scheme. So it asks how many clusters to split into, then it really gets stuck there. It just takes too long (especially when there are  a large number of spikes in the cluster - several minutes) until it generates the plots in the split view. Can we expedite or skip this process? This is an additional step added recently, do people find this additional information useful when they split?

**Comment by aliddell** [comment]
I'm not sure who finds it useful beyond its implementers, but I added it in by the request of people who wanted to see Tim et al.'s changes. In retrospect, it maybe should not be default behavior. Hopefully at the next spike sorting meeting we can discuss what's useful and what's not useful of these changes.

I'll push a patch later today which will make this an opt-in parameter.

**Comment by aliddell** [comment]
Right, give the latest version a pull and let me know how that works for you.
