### ISSUE TITLE
how to set uV_per_bit

### ISSUE THREAD

**Issue by yurikadoi** [JaneliaSciComp/JRCLUST#62]
When I try to make a parameter file, it asks me to put uV_per_bit value.
The default seems to be 1, but do you have any recommendations on how to set this value?
I am doing tetrode recording with openephys.
Thanks!
![capture](https://user-images.githubusercontent.com/14898551/48739511-378f9500-ec22-11e8-839a-0659bcd25c83.PNG)

**Comment by aliddell** [comment]
If you know the voltage range of your ADC and the gain on your amplifier, you can compute it via:
```
10^6 * (Vmax - Vmin)/2^nBits/gain
```

where `nBits` is the number of bits in your stored data type (e.g., 16 for int16)

**Comment by aliddell** [comment]
Hi @yurikadoi, did this help or was there any other information I can provide?
