### ISSUE TITLE
Error: when we say yes to "would you like to export advanced parameters", the prm file becomes empty

### ISSUE THREAD

**Issue by hideinagaki** [JaneliaSciComp/JRCLUST#82]

**Comment by aliddell** [comment]
Can you grab the commit hash for me? You can use `git log -n1` in git bash.

**Comment by hideinagaki** [comment]
I downloaded zip file instead of git clone. Now I git clone, I don't have this issue anymore.

**Comment by aliddell** [comment]
Great!
