### ISSUE TITLE
Channel numbers to ignore instaead of site numbers

### ISSUE THREAD

**Issue by LiuDaveLiu** [JaneliaSciComp/JRCLUST#83]
From raw recordings, it's straightforward to figure out the channels to ignore rather than the sites to ignore. It would be good to have this in the param file rather than having to figure out the conversion.

**Comment by jamesjun** [comment]
It's already implemented unless taken out. Please set viChanZero instead of
viSiteZero. Note that channel numbers start with 1.

-James

**Comment by aliddell** [comment]
Yeah I must have taken this out. Can't imagine why. I'll add it back in.
