### ISSUE TITLE
Some sites are not ignored

### ISSUE THREAD

**Issue by LiuDaveLiu** [JaneliaSciComp/JRCLUST#84]
The .prm is the same as provided in the email. I tried to ignore sites [200:374].

#### Output of `ver`
----------------------------------------------------------------------------------------------------
MATLAB Version: 9.2.0.556344 (R2017a)
MATLAB License Number: 698926
Operating System: Microsoft Windows 10 Pro Version 10.0 (Build 16299)
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.2         (R2017a)
Curve Fitting Toolbox                                 Version 3.5.5       (R2017a)
Image Processing Toolbox                              Version 10.0        (R2017a)
Neural Network Toolbox                                Version 10.0        (R2017a)
Parallel Computing Toolbox                            Version 6.10        (R2017a)
Signal Processing Toolbox                             Version 7.4         (R2017a)
Statistics and Machine Learning Toolbox               Version 11.1        (R2017a)
#### Output of `gpuDevice`
 CUDADevice with properties:

                      Name: 'GeForce GTX 1080 Ti'
                     Index: 1
         ComputeCapability: '6.1'
            SupportsDouble: 1
             DriverVersion: 9.2000
            ToolkitVersion: 8
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 1.1811e+10
           AvailableMemory: 9.6782e+09
       MultiprocessorCount: 28
              ClockRateKHz: 1670500
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 0
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1
#### The command you used

jrc preview E:\MAP\ww2\dl56\20181120\dl56_g0_t100.imec.ap.prm

#### Console output

![sitesignore](https://user-images.githubusercontent.com/8761973/52499926-a7bb1080-2baa-11e9-80aa-774f8f668330.jpg)

**Comment by jamesjun** [comment]
You might be better off creating a new map containing the bottom half of
the probe Please run `jrc probe imec3_opt3_195_245.prb` or see the probe
file `probe\imec3_opt3_195_245.prb`

-James

**Comment by jamesjun** [comment]
See how I subselected the channels on line 1.

https://github.com/JaneliaSciComp/JRCLUST/blob/master/probes/imec3_opt3_195_245.prb

-James

**Comment by LiuDaveLiu** [comment]
This have not been an issue in v3.3.0 of JRCLust. I only noticed this in v4.

**Comment by aliddell** [comment]
Yeah I must have taken this out. Can't imagine why. I'll add it back in.

**Comment by aliddell** [comment]
Fixed in b742df7
