### ISSUE TITLE
Error is v4 while saving

### ISSUE THREAD

**Issue by LiuDaveLiu** [JaneliaSciComp/JRCLUST#86]
Error while saving in manual curation

If you have a usage or support question, come join our [Gitter](https://gitter.im/JRCLUST/community) and ask your question there.
If you found a bug, please provide **all** of the following:

#### Output of `ver`
Same as before
#### Output of `gpuDevice`
Same as before
#### The command you used
(e.g., `jrc detect-sort myparam.prm`)
Same as before
#### If manually sorting, what it is you tried to do
Save
#### Console output
Error using jrclust.controllers.curate.CurateController/saveFiles
Too many input arguments.

Error in jrclust.controllers.curate.CurateController>@(varargin)obj.saveFiles(varargin{:}) (line
641)
            uimenu(obj.hMenus('FileMenu'), 'Label', 'Save', 'Callback', @obj.saveFiles);
 
Error while evaluating Menu Callback.

**Comment by aliddell** [comment]
Were you at least able to save when you exited?

**Comment by LiuDaveLiu** [comment]
Yes, I was able to save when I exited, so this is a low priority issue.

**Comment by aliddell** [comment]
Fixed in b742df7
